export { default as guchitter_1 } from './guchitter/guchitter_caption_1.png'
export { default as guchitter_2 } from './guchitter/guchitter_caption_2.png'
export { default as guchitter_3 } from './guchitter/guchitter_caption_3.png'
export { default as manage_stock_1 } from './manage-stock/manage-stock_caption_1.png'
export { default as manage_stock_2 } from './manage-stock/manage-stock_caption_2.png'
export { default as manage_stock_3 } from './manage-stock/manage-stock_caption_3.png'